'''
Euler Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

'''
pentangonal_numbers = []
for i in range(1,3000):
    pentangonal_numbers += [int( (.5) * i * ( (3 * i) - 1) )]


for j in range(len(pentangonal_numbers)):
    Pj = pentangonal_numbers[j]
    for k in range(i):
        Pk = pentangonal_numbers[k]

        pDiff = abs(Pj-Pk)
        if pDiff in pentangonal_numbers:
            pSum = Pk + Pj
            if pSum in pentangonal_numbers:
                print Pk, Pj
                break
