'''

Euler Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	                   Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

'''

triangle_numbers = []
pentagonal_numbers = []
hexagonal_numbers = []

for i in range(1,100001):
    pentagonal_numbers += [int( ((.5) * i * ((3 * i) - 1)) )]
    hexagonal_numbers += [int( ( i * ((2*i)-1)) )]
    t = int( ((.5) * i * (i+1)) )
    triangle_numbers += [t]
    
    if t in pentagonal_numbers and t in hexagonal_numbers:
        print t
        print i
